#!/bin/bash
LOG=/tmp/fix-vmdk.log
LOG_ERR=/tmp/fix-vmdk-error.log
DRY=""

cd "$1"
CHK=`ls *0*.vmdk| wc -l`
if [ ${CHK:-0} -eq 0 ]; then
    echo "Target: $PWD"
    echo "$0 /path/to/vmwarevm_dir"
    exit 0
fi

cat /dev/null > $LOG
cat /dev/null > $LOG_ERR
echo "Log files: $LOG $LOG_ERR
for i in `ls *0*.vmdk`
do
    echo "`date +%F-%T`: $i start." |tee -a $LOG
    $DRY dd if="$i" of="/tmp/$i" conv=noerror,sync >> $LOG_ERR 2>&1
    CODE=$?
    echo "`date +%F-%T`: $i finished with CODE: $CODE." |tee -a $LOG
    if [ $CODE = 0 ]; then
        $DRY /bin/mv /tmp/$i $i
    else
        $DRY /bin/rm /tmp/$i
    fi
done
