#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

tempfile="$( mktemp )"

for p in $( pgrep \.vmx )
do
    ps -p "$p" -o pid -o %cpu -o %mem -o command >> "$tempfile"
done

if [ ! -s "$tempfile" ]; then
    echo "No vm runs."
    exit 0
else
    grep '%' "$tempfile" | sort | uniq | tr -d '%' | sed s/COMMAND/VM_FILE/g    > "${tempfile}-1"
    grep -v '%' "$tempfile" | tr '/' ' ' | awk '{ print $1,$2,$3,$NF }' | sort >> "${tempfile}-1"
    column -t "${tempfile}-1"
fi
rm -f  "$tempfile" "${tempfile}-1"
