#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

# Check
if [ -x "/Applications/VMware Fusion Tech Preview.app/Contents/Library/vmrun" ] ; then
        VMRUN="/Applications/VMware Fusion Tech Preview.app/Contents/Library/vmrun"
        : "VMware Fusion TechPreview was found"
elif [ -x "/Applications/VMware Fusion.app/Contents/Library/vmrun" ] ;then
        VMRUN="/Applications/VMware Fusion.app/Contents/Library/vmrun"
        : "VMWre fusion was found."
else
        echo "Nt found: vmrun. Bye"
        exit 0
fi

PlistBuddy -c 'print fusionStartMenuVmList' $plist  | grep cachePath | awk '$1 =""; $2="";{print $0}' |grep -wi oPENSTEP42

plist="${HOME}/Library/Preferences/com.vmware.fusionStartMenu.plist"
if [ ! -f "$plist" ]; then
    echo "Not found: $plist"
    exit 1
fi

vmname="$1"
if [ -z "$vmname" ]; then
    vmname="$( uuidgen )"
fi

if [ "$( echo "$2" | tr "[:upper:]" "[:lower:]" )" = nogui ]; then
    mode=nogui
else
    mode=gui
fi

if [ -f "$vmname" ]; then
    if [ "$( echo "$vmname" | awk -F. '{print $NF}' )" = vmx ]; then
        file_path="$vmname"
        vmname="$( basename "${vmname/.vmx/}" )"
    else
        file_path=x
    fi
elif [ -d "$vmname" ]; then
    if [ "$( echo "$vmname" | awk -F. '{print $NF}' )" = vmwarevm ]; then
        file_path="$vmname"
        vmname="$( basename "${vmname/.vmwarevm/}" )"
    else
        file_path=x
    fi
elif [ -d "${vmname}.vmwarevm" ]; then
    file_path="${vmname}.vmwarevm"
    vmname="$( basename "${vmname}" )"
else
    file_path="$(
        /usr/libexec/PlistBuddy -c "print fusionStartMenuVmList" "$plist" \
        | grep cachePath \
        | awk '$1 = ""; $2 = ""; {print $0}' \
        | grep -wi "$vmname" \
        | awk '{$1 = $1};1' \
        | awk -F '/' '$NF = "";OFS = "/"  {print $0}' \
        | sed -e 's!/*$!!g'
    )"
fi

tempfile="$( mktemp )"
"$VMRUN" list | awk -F"[./]" '$NF == "vmx" { print $(NF-1)}' | sort > "${tempfile}-1"

if [ "${file_path:-x}" = x ]; then
    vmdir="$(
        /usr/libexec/PlistBuddy -c "print fusionStartMenuVmList" "$plist" \
        | grep cachePath \
        | awk '$1 = ""; $2 = ""; {print $0}' \
        | awk '{$1 = $1};1' \
        | awk -F '/' '$NF = ""; $(NF -1) = ""; OFS = "/"  {print $0}' \
        | sed -e 's!/*$!!g' \
        | sort | uniq | head -1
    )"

    stat -f %N "${vmdir}/"*.vmwarevm | awk -F"[./]" '{print $(NF - 1)}' | sort > "$tempfile"
    comm -23 "$tempfile" "${tempfile}-1"
    /bin/echo -n "Choose one(mode: $mode): "
    while read -r vmname
    do
        if [ -d "${vmdir}/${vmname}.vmwarevm" ]; then
            file_path="${vmdir}/${vmname}.vmwarevm"
            break
        fi
        /bin/echo -n "Choose one: "
    done
fi

if [ -n "$( awk -v V="$vmname" '$1 == V {print NR }' "${tempfile}-1" )" ]; then
    echo "$vmname ($file_path) is already running."
else
    echo "Start $vmname($file_path). mode: $mode"
    "$VMRUN" -T fusion start "$file_path" "$mode"
fi
rm -f "$tempfile" "${tempfile}-1"
